apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-service
  template:
    metadata:
      labels:
        app: blockchain-service
    spec:
      containers:
        - name: blockchain-service
          image: eduverse/blockchain-service:latest
          ports:
            - containerPort: 5000
